services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    command: ["mongod", "--auth", "--bind_ip_all"]
    ports:
      - "27017:27017"      # <-- this line publishes it to your host
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db

  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

  kowloon:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - minio
    volumes:
      - ./init:/init

volumes:
  mongo-data:
  minio-data:
